name: Check Pull Request Title
# This is a basic workflow to help you get started with Actions
on:
  pull_request:
    branches: ["testing/incy", "testing/kiwi", "master"]
    types: ["opened", "edited", "reopened"]

env:
  MASTER_BRANCH: "master"
  TESTING_BRANCHES: ("testing/incy" "testing/kiwi")
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  check_pr_title_testing_series:
    # The type of runner that the job will run on
    name: aaa
    if: ${{ env.MASTER_BRANCH == 'master' }}
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    # echo ${{github.event.pull_request.title}}
    steps:
      - run: echo "check testing/incy"
      - uses: Slashgear/action-check-pr-title@v4.3.0
        with:
          regexp: ${{ vars.TEAM_MAOTAI_PR_TITLE_REGEX }} # Regex the title should match.^(?:[A-Z]{3,5}-\\d{1,9}|refactor|Revert|docs|sentry|test|ci|build|style|release|perf).*$